name: Build Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
       
        distribution: 'adopt' 

    - name: List contents of the directory
      run: ls -l
      working-directory: Student_project
      
    - name: Build with Maven
      run: mvn clean install
      working-directory: Student_project

    - name: Run tests
      run: mvn test
      working-directory: Student_project
